name: ci
on:
  push:
    branches: [ main ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
  test:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - run: npm test
  build:
    runs-on: ubuntu-latest
    needs: [ setup ]
    steps:
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/MoneoApp/web:latest
